counter/urls.py
from django.urls import path

from . import views

app_name = 'counter'
urlpatterns = [
	# # ex: /polls/
	path('', views.Home.as_view(), name='index'),
	# # ex: /polls/5/
	path('add_counter/<int:metrics_id>/', 
		views.CreateCounter.as_view(), name='add_counter'),
	path('metrics/', 
		views.CreateMetrics.as_view(), name='add_metrics'),
	path('view_counter/<int:metrics_id>/', 
		views.CounterView.as_view(), name='view_counter'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('counter.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
]

counter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Metrics(models.Model):
	SCOPE_CHOICES = (
		(None, 'scope default'),
		('private', 'Private'),
		('public', 'Public'),
	)
	name = models.CharField(max_length=80, unique=True)
	title = models.CharField(max_length=200,)
	quantity_name = models.CharField(max_length=80,)
	created_by = models.ForeignKey(User, related_name='%(class)s_created_by', 
		on_delete=models.CASCADE)
	scope = models.CharField(max_length=80, choices=SCOPE_CHOICES)
	duration = models.DurationField()

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Counters(models.Model):
	user = models.ForeignKey(User, related_name='%(class)s_user', 
		on_delete=models.CASCADE)
	metrics = models.ForeignKey(Metrics, related_name='%(class)s_metrics', 
		on_delete=models.CASCADE)
	data_value = models.DecimalField(max_digits=10, decimal_places=2, default=0)
	created_on = models.DateTimeField(auto_now_add=True,)

	def __str__(self):
		return str(self.data_value)

counter/forms.py
from django import forms
from django.conf import settings
from counter.models import *

def get_counter_form(quantity):
	class CounterForm(forms.ModelForm):
		def __init__(self, *args, **kwargs):
			super(CounterForm, self).__init__(*args, **kwargs)
			self.fields['data_value'].label = quantity
			self.fields['user'].widget = forms.HiddenInput()
			self.fields['metrics'].widget = forms.HiddenInput()

		class Meta(object):
			model = Counters
			fields = ('data_value', 'user', 'metrics')

	return CounterForm

class MetricsForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['created_by'].widget = forms.HiddenInput()
		
	class Meta(object):
		model = Metrics
		fields = '__all__'

counter/views.py
from django.shortcuts import render
from django.db.models import Q 
from django.views.generic import TemplateView
from django.utils import timezone
from django.urls import reverse_lazy 
from counter.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from .forms import *
from django.core.exceptions import PermissionDenied



class CreateMetrics(LoginRequiredMixin, CreateView):
	model = Metrics
	template_name = 'counter/create_metrics.html'
	success_url = reverse_lazy('counter:index')
	form_class = MetricsForm

	def get_initial(self):
		return {'created_by':self.request.user,}

class CreateCounter(LoginRequiredMixin, CreateView):
	model = Counters
	template_name = 'counter/create_counter.html'
	success_url = reverse_lazy('counter:index')
	
	def get_form_class(self):
		return get_counter_form(self.metrics.quantity_name)

	def get_initial(self):
		return {
			'user':self.request.user,
			'metrics':self.metrics
		}

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['metrics'] = self.metrics
		return context

	def get(self, request, metrics_id, *args, **kwargs):
		self.metrics = Metrics.objects.get(pk=metrics_id)
		counter = Counters.objects.filter(
			metrics=self.metrics, 
			user=self.request.user
		)
		if not counter.exists() or counter.exists() and (timezone.now() - counter.last().created_on) >= self.metrics.duration:
			return super().get(request, *args, **kwargs)
		else :
			raise PermissionDenied

	def post(self, request, metrics_id, *args, **kwargs):
		self.metrics = Metrics.objects.get(pk=metrics_id)
		return super().post(request, *args, **kwargs)

class CounterView(LoginRequiredMixin, TemplateView):
	template_name = 'counter/counter_view.html'

	def get(self, request, metrics_id, *args, **kwargs):
		self.metrics = Metrics.objects.get(pk=metrics_id)
		return super().get(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['metrics'] = self.metrics
		context['user_counters'] = Counters.objects.filter(user=self.request.user,metrics=self.metrics)

		return context

class Home(LoginRequiredMixin, TemplateView):
	template_name = 'counter/home.html'
	def get_context_data(self, *args, **kwargs):
		context = super(Home, self).get_context_data(*args, **kwargs)
		metrics = Metrics.objects.filter(
			Q(created_by=self.request.user)|
			Q(scope='public')|
			Q(scope__isnull=True)
		)
		metrics_list = []
		for x in metrics.iterator():
			counter = Counters.objects.filter(
				metrics=x, 
				user=self.request.user
			)
			if not counter.exists() or counter.exists() and (timezone.now() - counter.last().created_on) >= x.duration:
				metrics_list.append(x)

		context['metrics_list'] = metrics_list
		context['all_metrices'] = metrics 
		return context

counter/templates/counter/counter_view.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<script src="https://code.highcharts.com/highcharts.src.js"></script>
	<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: '{{metrics.title}}'
        },
        xAxis: {
            categories: ['{{metrics.quantity_name}}']
        },
        series: [{
            name: '{{metrics.name}}',
             data: [
	            {% for x in user_counters %}
		            {{ x.data_value }}
		            {% if not forloop.last %}, {% endif %}
	            {% endfor %}
          ]
        }]
    });
  </script>

</body>
</html>	

<!DOCTYPE HTML>
<html>
<head>
<script type="text/javascript">
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
    theme: "light1", // "light2", "dark1", "dark2"
    animationEnabled: false, // change to true
    title:{
        text: "{{metrics.title}}"
    },
    data: [
    {
        // Change type to "bar", "area", "spline", "pie",etc.
        type: "column",
        dataPoints: [
                {% for x in user_counters %}
                    { label: "{{ x.created_on }}",  y: {{ x.data_value }}  }
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
          ]
    }
    ]
});
chart.render();

}
</script>
</head>
<body>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"> </script>
</body>
</html>
	

counter/templates/counter/create_counter.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h3> Metrics to update: </h3>
	<form method="post">
		{% csrf_token %}
		{{form}}
		<input type="submit" name="submit" value="add counter">
	</form>

{% endblock content %}

counter/templates/counter/create_metrics.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<br>
	<h3 class="text-center"><strong>Create Metrics:</strong></h3>
	<form method="post" action="{% url 'counter:add_metrics' %}">
		{% csrf_token %}
		<div class="row">
		 	<div class="col-md-8 col-md-offset-3">
			  	<table>
					{{form}}	
				</table>
			</div>
  		</div>
  		<br>
  		<center>
			<button type="submit">Add</button>
		</center>
		<br>
	</form>
	<br>
</div>
{% endblock content %}

counter/templates/counter/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h3> Metrics to update </h3>
	<table class="table">
		<tr>
			<th>Counter</th>
			<th>Insert</th>
		</tr>
		{% for x in metrics_list %}
			<tr>
				<td>{{x.name}}</td>
				<td>
					<a class="btn btn-default"href="{% url 'counter:add_counter' x.pk %}">
					Add <i class="fas fa-plus-circle "></i>
					</a>
				</td>
			</tr>
		{% endfor %}
	</table>
	<p>
		<a  class="btn btn-success" href="{% url 'counter:add_metrics' %}">
		create metrics <i class="fas fa-plus-circle "></i>
		</a>
	</p>

	<br>

	<h3>All Metrics you participated</h3>

	<table class="table">
		<tr>
			<th>Metrics</th>
			<th>Display</th>
		</tr>
		{% for x in all_metrices %}
			<tr>
				<td>{{x.name}}</td>
				<td>
					<a target="_blank" class="btn btn-default" href="{% url 'counter:view_counter' x.pk %}">
						View <i class="fas fa-eye "></i>
					</a>
				</td>
			</tr>
		{% endfor %}
	</table>
	<br>
	<br>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 { 
      background-color: #1abc9c; /* Green */
      color: #ffffff;
  }
  .bg-2 { 
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 { 
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-4 { 
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }
  html{
    position: relative;
    min-height: 100%;
  }

  body{
    margin:0 0 100px;
  }

  footer{
    position: absolute;
    left: 0;
    bottom: 0;
    height: 100px;
    width: 100%;
    overflow: hidden;
  }

  .errorlist{
    color: red;
    list-style: none;
    padding-left: 0;
  }
  </style>

  <title>
  {% block title %}Metrics{% endblock %}
  </title>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Counter</a>
    </div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
      	{% block nav %}
      			
        		{% if request.user.is_authenticated %}
        			<li><a href="{% url 'counter:index' %}">main page</a></li>
              <li><a href="{% url 'auth_logout' %}">logout</a><li>
        		{% else %}
        			<li><a href="{% url 'auth_login' %}">login</a><li>
              <li><a href="{% url 'registration_register' %}">signup</a></li>
        		{% endif %}

        {% endblock %}
      </ul>
    </div>
    
  </div>
</nav>

<!-- First Container -->
<div class="container bg-3">
<br><br>
 {% block content %}
 Main Text
 {% endblock %}
</div>
<br><br>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p></p> 
</footer>

</body>
</html>